### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Not0xAstral** [MrUnknown11/SFS-ThrustMod#1]
![Screenshot (106)](https://user-images.githubusercontent.com/96470356/168452613-60de8e6e-f993-408e-b40d-392c40f23ff7.png)

**Comment by MrUnknown11** [comment]
How did you get this? I tried a lot of times but I never saw a bug like that.

**Comment by Not0xAstral** [comment]
> How did you get this? I tried a lot of times but I never saw a bug like that.

all i did was to click "Revert To Build"

**Comment by MrUnknown11** [comment]
> > How did you get this? I tried a lot of times but I never saw a bug like that.
> 
> all i did was to click "Revert To Build"

Try now. https://github.com/MrUnknown11/SFS-ThrustMod/releases/tag/SFS-UnknownMod
