### ISSUE TITLE
Bug #2 

### ISSUE THREAD

**Issue by Not0xAstral** [MrUnknown11/SFS-ThrustMod#2]
![Screenshot (112)](https://user-images.githubusercontent.com/96470356/168497983-0cdf54ce-ca1b-4bcf-b734-72726c426ca1.png)

**Comment by Not0xAstral** [comment]
only fixes if i restart sfs

**Comment by MrUnknown11** [comment]
> only fixes if i restart sfs

It should have been fixed with the other bug. 
try now.  https://github.com/MrUnknown11/SFS-ThrustMod/releases/tag/SFS-UnknownMod
